platform: linux/arm

workspace:
  base: /go
  path: src/github.com/abaeve/auth-srv

clone:
  default:
    image: plugins/git:linux-arm
    depth: 50
    tags: true

pipeline:
  build:
    image: registry.maurer-it.net/golang-1.8
    commands:
      - go get -t -v ./...
      - go get github.com/mattn/goveralls
#      - goveralls -service=drone.io -ignore=discord/discord.go,main.go -repotoken=${repotoken}
      - CGO_ENABLED=0 go build -ldflags "-X main.Version=$(git describe --abbrev=0 --tags)-${DRONE_BUILD_NUMBER}-$(git rev-parse --short HEAD)" -o auth-srv .

  publish:
    image: plugins/docker:linux-arm
    repo: registry.maurer-it.net/auth-srv
    registry: registry.maurer-it.net
    secrets:
      - source: registry_user
        target: PLUGIN_USERNAME
      - source: registry_pass
        target: PLUGIN_PASSWORD
    tags: [ latest, 1.0.2 ]
    when:
      event: [ tag ]

  publish-snapshot:
    image: plugins/docker:linux-arm
    repo: registry.maurer-it.net/auth-srv
    registry: registry.maurer-it.net
    secrets:
      - source: registry_user
        target: PLUGIN_USERNAME
      - source: registry_pass
        target: PLUGIN_PASSWORD
    tags: [ latest, 1.0.2-SNAPSHOT ]
    when:
      branch: [ release/* ]

  deploy-test:
    image: registry.maurer-it.net/drone-ssh
    host: docker1.home
    username: pi
    secrets:
      - source: SSH_KEY
        target: ssh_key
    port: 22
    script:
      - docker login -u ${registry_user} -p ${registry_pass} registry.maurer-it.net
      - docker service update --with-registry-auth --image=registry.maurer-it.net/auth-srv:1.0.2-SNAPSHOT auth-srv-dev
    when:
      branch: [ release/* ]

  deploy-prod:
    image: registry.maurer-it.net/drone-ssh
    host: docker1.home
    username: pi
    secrets:
      - source: SSH_KEY
        target: ssh_key
    port: 22
    script:
      - docker login -u ${registry_user} -p ${registry_pass} registry.maurer-it.net
      - docker service create --name auth-srv --network chremoas --with-registry-auth registry.maurer-it.net/auth-srv:1.0.2
    when:
      event: deployment
      environment: production