language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/abaeve/services-common/config
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci -ignore=proto/auth-srv.pb.go,main.go