language: go
sudo: false
services:
  - mysql
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/abaeve/services-common/config
  - mysql -e 'CREATE DATABASE authservices;'
  - mysql -u root --default-character-set=utf8 authservices < sql/ddl.sql
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci -ignore=proto/auth-srv.pb.go,main.go