// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/abaeve/auth-srv/repository (interfaces: AccessesRepository,AllianceRepository,CorporationRepository,CharacterRepository,UserRepository,RoleRepository,AuthenticationCodeRepository)

package mocks

import (
	model "github.com/abaeve/auth-srv/model"
	gomock "github.com/golang/mock/gomock"
)

// Mock of AllianceRepository interface
type MockAllianceRepository struct {
	ctrl     *gomock.Controller
	recorder *_MockAllianceRepositoryRecorder
}

// Recorder for MockAllianceRepository (not exported)
type _MockAllianceRepositoryRecorder struct {
	mock *MockAllianceRepository
}

func NewMockAllianceRepository(ctrl *gomock.Controller) *MockAllianceRepository {
	mock := &MockAllianceRepository{ctrl: ctrl}
	mock.recorder = &_MockAllianceRepositoryRecorder{mock}
	return mock
}

func (_m *MockAllianceRepository) EXPECT() *_MockAllianceRepositoryRecorder {
	return _m.recorder
}

func (_m *MockAllianceRepository) Save(alliance *model.Alliance) error {
	ret := _m.ctrl.Call(_m, "Save", alliance)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAllianceRepositoryRecorder) Save(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Save", arg0)
}

func (_m *MockAllianceRepository) FindByAllianceId(allianceId int64) *model.Alliance {
	ret := _m.ctrl.Call(_m, "FindByAllianceId", allianceId)
	ret0, _ := ret[0].(*model.Alliance)
	return ret0
}

func (_mr *_MockAllianceRepositoryRecorder) FindByAllianceId(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FindByAllianceId", arg0)
}

func (_m *MockAllianceRepository) FindAll() []*model.Alliance {
	ret := _m.ctrl.Call(_m, "FindAll")
	ret0, _ := ret[0].([]*model.Alliance)
	return ret0
}

func (_mr *_MockAllianceRepositoryRecorder) FindAll() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FindAll")
}

// Mock of CorporationRepository interface
type MockCorporationRepository struct {
	ctrl     *gomock.Controller
	recorder *_MockCorporationRepositoryRecorder
}

// Recorder for MockCorporationRepository (not exported)
type _MockCorporationRepositoryRecorder struct {
	mock *MockCorporationRepository
}

func NewMockCorporationRepository(ctrl *gomock.Controller) *MockCorporationRepository {
	mock := &MockCorporationRepository{ctrl: ctrl}
	mock.recorder = &_MockCorporationRepositoryRecorder{mock}
	return mock
}

func (_m *MockCorporationRepository) EXPECT() *_MockCorporationRepositoryRecorder {
	return _m.recorder
}

func (_m *MockCorporationRepository) Save(corporation *model.Corporation) error {
	ret := _m.ctrl.Call(_m, "Save", corporation)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockCorporationRepositoryRecorder) Save(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Save", arg0)
}

func (_m *MockCorporationRepository) FindByCorporationId(corporationId int64) *model.Corporation {
	ret := _m.ctrl.Call(_m, "FindByCorporationId", corporationId)
	ret0, _ := ret[0].(*model.Corporation)
	return ret0
}

func (_mr *_MockCorporationRepositoryRecorder) FindByCorporationId(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FindByCorporationId", arg0)
}

func (_m *MockCorporationRepository) FindAll() []*model.Corporation {
	ret := _m.ctrl.Call(_m, "FindAll")
	ret0, _ := ret[0].([]*model.Corporation)
	return ret0
}

func (_mr *_MockCorporationRepositoryRecorder) FindAll() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FindAll")
}

// Mock of CharacterRepository interface
type MockCharacterRepository struct {
	ctrl     *gomock.Controller
	recorder *_MockCharacterRepositoryRecorder
}

// Recorder for MockCharacterRepository (not exported)
type _MockCharacterRepositoryRecorder struct {
	mock *MockCharacterRepository
}

func NewMockCharacterRepository(ctrl *gomock.Controller) *MockCharacterRepository {
	mock := &MockCharacterRepository{ctrl: ctrl}
	mock.recorder = &_MockCharacterRepositoryRecorder{mock}
	return mock
}

func (_m *MockCharacterRepository) EXPECT() *_MockCharacterRepositoryRecorder {
	return _m.recorder
}

func (_m *MockCharacterRepository) Save(character *model.Character) error {
	ret := _m.ctrl.Call(_m, "Save", character)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockCharacterRepositoryRecorder) Save(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Save", arg0)
}

func (_m *MockCharacterRepository) FindByCharacterId(characterId int64) *model.Character {
	ret := _m.ctrl.Call(_m, "FindByCharacterId", characterId)
	ret0, _ := ret[0].(*model.Character)
	return ret0
}

func (_mr *_MockCharacterRepositoryRecorder) FindByCharacterId(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FindByCharacterId", arg0)
}

func (_m *MockCharacterRepository) FindByAutenticationCode(authCode string) *model.Character {
	ret := _m.ctrl.Call(_m, "FindByAutenticationCode", authCode)
	ret0, _ := ret[0].(*model.Character)
	return ret0
}

func (_mr *_MockCharacterRepositoryRecorder) FindByAutenticationCode(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FindByAutenticationCode", arg0)
}

func (_m *MockCharacterRepository) FindAll() []*model.Character {
	ret := _m.ctrl.Call(_m, "FindAll")
	ret0, _ := ret[0].([]*model.Character)
	return ret0
}

func (_mr *_MockCharacterRepositoryRecorder) FindAll() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FindAll")
}

// Mock of UserRepository interface
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *_MockUserRepositoryRecorder
}

// Recorder for MockUserRepository (not exported)
type _MockUserRepositoryRecorder struct {
	mock *MockUserRepository
}

func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &_MockUserRepositoryRecorder{mock}
	return mock
}

func (_m *MockUserRepository) EXPECT() *_MockUserRepositoryRecorder {
	return _m.recorder
}

func (_m *MockUserRepository) Save(user *model.User) error {
	ret := _m.ctrl.Call(_m, "Save", user)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockUserRepositoryRecorder) Save(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Save", arg0)
}

func (_m *MockUserRepository) FindByChatId(chatId string) *model.User {
	ret := _m.ctrl.Call(_m, "FindByChatId", chatId)
	ret0, _ := ret[0].(*model.User)
	return ret0
}

func (_mr *_MockUserRepositoryRecorder) FindByChatId(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FindByChatId", arg0)
}

func (_m *MockUserRepository) LinkCharacterToUserByAuthCode(authCode string, user *model.User) error {
	ret := _m.ctrl.Call(_m, "LinkCharacterToUserByAuthCode", authCode, user)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockUserRepositoryRecorder) LinkCharacterToUserByAuthCode(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LinkCharacterToUserByAuthCode", arg0, arg1)
}

// Mock of RoleRepository interface
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *_MockRoleRepositoryRecorder
}

// Recorder for MockRoleRepository (not exported)
type _MockRoleRepositoryRecorder struct {
	mock *MockRoleRepository
}

func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &_MockRoleRepositoryRecorder{mock}
	return mock
}

func (_m *MockRoleRepository) EXPECT() *_MockRoleRepositoryRecorder {
	return _m.recorder
}

func (_m *MockRoleRepository) Save(role *model.Role) error {
	ret := _m.ctrl.Call(_m, "Save", role)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockRoleRepositoryRecorder) Save(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Save", arg0)
}

func (_m *MockRoleRepository) FindByRoleName(roleName string) *model.Role {
	ret := _m.ctrl.Call(_m, "FindByRoleName", roleName)
	ret0, _ := ret[0].(*model.Role)
	return ret0
}

func (_mr *_MockRoleRepositoryRecorder) FindByRoleName(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FindByRoleName", arg0)
}

func (_m *MockRoleRepository) FindAll() []*model.Role {
	ret := _m.ctrl.Call(_m, "FindAll")
	ret0, _ := ret[0].([]*model.Role)
	return ret0
}

func (_mr *_MockRoleRepositoryRecorder) FindAll() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FindAll")
}

func (_m *MockRoleRepository) Delete(roleName string) error {
	ret := _m.ctrl.Call(_m, "Delete", roleName)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockRoleRepositoryRecorder) Delete(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Delete", arg0)
}

// Mock of AuthenticationCodeRepository interface
type MockAuthenticationCodeRepository struct {
	ctrl     *gomock.Controller
	recorder *_MockAuthenticationCodeRepositoryRecorder
}

// Recorder for MockAuthenticationCodeRepository (not exported)
type _MockAuthenticationCodeRepositoryRecorder struct {
	mock *MockAuthenticationCodeRepository
}

func NewMockAuthenticationCodeRepository(ctrl *gomock.Controller) *MockAuthenticationCodeRepository {
	mock := &MockAuthenticationCodeRepository{ctrl: ctrl}
	mock.recorder = &_MockAuthenticationCodeRepositoryRecorder{mock}
	return mock
}

func (_m *MockAuthenticationCodeRepository) EXPECT() *_MockAuthenticationCodeRepositoryRecorder {
	return _m.recorder
}

func (_m *MockAuthenticationCodeRepository) Save(character *model.Character, authCode string) error {
	ret := _m.ctrl.Call(_m, "Save", character, authCode)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAuthenticationCodeRepositoryRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Save", arg0, arg1)
}
