// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth-srv.proto

/*
Package abaeve_auth is a generated protocol buffer package.

It is generated from these files:
	auth-srv.proto

It has these top-level messages:
	AuthCreateRequest
	AuthCreateResponse
	AuthConfirmRequest
	AuthConfirmResponse
	CharactersResponse
	Character
	CorporationsResponse
	Corporation
	AlliancesResponse
	Alliance
	EntityAdminResponse
	AllianceAdminRequest
	CorporationAdminRequest
	CharacterAdminRequest
	EntityQueryRequest
*/
package abaeve_auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EntityType int32

const (
	EntityType_ALLIANCE    EntityType = 0
	EntityType_CORPORATION EntityType = 1
	EntityType_CHARACTER   EntityType = 2
	EntityType_ROLE        EntityType = 3
)

var EntityType_name = map[int32]string{
	0: "ALLIANCE",
	1: "CORPORATION",
	2: "CHARACTER",
	3: "ROLE",
}
var EntityType_value = map[string]int32{
	"ALLIANCE":    0,
	"CORPORATION": 1,
	"CHARACTER":   2,
	"ROLE":        3,
}

func (x EntityType) String() string {
	return proto.EnumName(EntityType_name, int32(x))
}
func (EntityType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EntityOperation int32

const (
	EntityOperation_ADD_OR_UPDATE EntityOperation = 0
	EntityOperation_REMOVE        EntityOperation = 1
)

var EntityOperation_name = map[int32]string{
	0: "ADD_OR_UPDATE",
	1: "REMOVE",
}
var EntityOperation_value = map[string]int32{
	"ADD_OR_UPDATE": 0,
	"REMOVE":        1,
}

func (x EntityOperation) String() string {
	return proto.EnumName(EntityOperation_name, int32(x))
}
func (EntityOperation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AuthCreateRequest struct {
	Token       string       `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	Character   *Character   `protobuf:"bytes,2,opt,name=Character" json:"Character,omitempty"`
	Corporation *Corporation `protobuf:"bytes,3,opt,name=Corporation" json:"Corporation,omitempty"`
	Alliance    *Alliance    `protobuf:"bytes,4,opt,name=Alliance" json:"Alliance,omitempty"`
	AuthScope   []string     `protobuf:"bytes,5,rep,name=AuthScope" json:"AuthScope,omitempty"`
}

func (m *AuthCreateRequest) Reset()                    { *m = AuthCreateRequest{} }
func (m *AuthCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthCreateRequest) ProtoMessage()               {}
func (*AuthCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthCreateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthCreateRequest) GetCharacter() *Character {
	if m != nil {
		return m.Character
	}
	return nil
}

func (m *AuthCreateRequest) GetCorporation() *Corporation {
	if m != nil {
		return m.Corporation
	}
	return nil
}

func (m *AuthCreateRequest) GetAlliance() *Alliance {
	if m != nil {
		return m.Alliance
	}
	return nil
}

func (m *AuthCreateRequest) GetAuthScope() []string {
	if m != nil {
		return m.AuthScope
	}
	return nil
}

type AuthCreateResponse struct {
	AuthenticationCode string `protobuf:"bytes,1,opt,name=AuthenticationCode" json:"AuthenticationCode,omitempty"`
	Success            bool   `protobuf:"varint,2,opt,name=Success" json:"Success,omitempty"`
}

func (m *AuthCreateResponse) Reset()                    { *m = AuthCreateResponse{} }
func (m *AuthCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthCreateResponse) ProtoMessage()               {}
func (*AuthCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthCreateResponse) GetAuthenticationCode() string {
	if m != nil {
		return m.AuthenticationCode
	}
	return ""
}

func (m *AuthCreateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AuthConfirmRequest struct {
	UserId             string `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
	AuthenticationCode string `protobuf:"bytes,2,opt,name=AuthenticationCode" json:"AuthenticationCode,omitempty"`
}

func (m *AuthConfirmRequest) Reset()                    { *m = AuthConfirmRequest{} }
func (m *AuthConfirmRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthConfirmRequest) ProtoMessage()               {}
func (*AuthConfirmRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthConfirmRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AuthConfirmRequest) GetAuthenticationCode() string {
	if m != nil {
		return m.AuthenticationCode
	}
	return ""
}

type AuthConfirmResponse struct {
	Success       bool   `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	CharacterName string `protobuf:"bytes,2,opt,name=CharacterName" json:"CharacterName,omitempty"`
}

func (m *AuthConfirmResponse) Reset()                    { *m = AuthConfirmResponse{} }
func (m *AuthConfirmResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthConfirmResponse) ProtoMessage()               {}
func (*AuthConfirmResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AuthConfirmResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AuthConfirmResponse) GetCharacterName() string {
	if m != nil {
		return m.CharacterName
	}
	return ""
}

type CharactersResponse struct {
	List []*Character `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
}

func (m *CharactersResponse) Reset()                    { *m = CharactersResponse{} }
func (m *CharactersResponse) String() string            { return proto.CompactTextString(m) }
func (*CharactersResponse) ProtoMessage()               {}
func (*CharactersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CharactersResponse) GetList() []*Character {
	if m != nil {
		return m.List
	}
	return nil
}

type Character struct {
	Id            int64  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	CorporationId int64  `protobuf:"varint,3,opt,name=CorporationId" json:"CorporationId,omitempty"`
}

func (m *Character) Reset()                    { *m = Character{} }
func (m *Character) String() string            { return proto.CompactTextString(m) }
func (*Character) ProtoMessage()               {}
func (*Character) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Character) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Character) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Character) GetCorporationId() int64 {
	if m != nil {
		return m.CorporationId
	}
	return 0
}

type CorporationsResponse struct {
	List []*Corporation `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
}

func (m *CorporationsResponse) Reset()                    { *m = CorporationsResponse{} }
func (m *CorporationsResponse) String() string            { return proto.CompactTextString(m) }
func (*CorporationsResponse) ProtoMessage()               {}
func (*CorporationsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CorporationsResponse) GetList() []*Corporation {
	if m != nil {
		return m.List
	}
	return nil
}

type Corporation struct {
	Id         int64  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Ticker     string `protobuf:"bytes,3,opt,name=Ticker" json:"Ticker,omitempty"`
	AllianceId int64  `protobuf:"varint,4,opt,name=AllianceId" json:"AllianceId,omitempty"`
}

func (m *Corporation) Reset()                    { *m = Corporation{} }
func (m *Corporation) String() string            { return proto.CompactTextString(m) }
func (*Corporation) ProtoMessage()               {}
func (*Corporation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Corporation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Corporation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Corporation) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *Corporation) GetAllianceId() int64 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

type AlliancesResponse struct {
	List []*Alliance `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
}

func (m *AlliancesResponse) Reset()                    { *m = AlliancesResponse{} }
func (m *AlliancesResponse) String() string            { return proto.CompactTextString(m) }
func (*AlliancesResponse) ProtoMessage()               {}
func (*AlliancesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AlliancesResponse) GetList() []*Alliance {
	if m != nil {
		return m.List
	}
	return nil
}

type Alliance struct {
	Id     int64  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Ticker string `protobuf:"bytes,3,opt,name=Ticker" json:"Ticker,omitempty"`
}

func (m *Alliance) Reset()                    { *m = Alliance{} }
func (m *Alliance) String() string            { return proto.CompactTextString(m) }
func (*Alliance) ProtoMessage()               {}
func (*Alliance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Alliance) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Alliance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Alliance) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

type EntityAdminResponse struct {
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
}

func (m *EntityAdminResponse) Reset()                    { *m = EntityAdminResponse{} }
func (m *EntityAdminResponse) String() string            { return proto.CompactTextString(m) }
func (*EntityAdminResponse) ProtoMessage()               {}
func (*EntityAdminResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *EntityAdminResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AllianceAdminRequest struct {
	Alliance  *Alliance       `protobuf:"bytes,1,opt,name=Alliance" json:"Alliance,omitempty"`
	Operation EntityOperation `protobuf:"varint,2,opt,name=Operation,enum=abaeve.auth.EntityOperation" json:"Operation,omitempty"`
}

func (m *AllianceAdminRequest) Reset()                    { *m = AllianceAdminRequest{} }
func (m *AllianceAdminRequest) String() string            { return proto.CompactTextString(m) }
func (*AllianceAdminRequest) ProtoMessage()               {}
func (*AllianceAdminRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AllianceAdminRequest) GetAlliance() *Alliance {
	if m != nil {
		return m.Alliance
	}
	return nil
}

func (m *AllianceAdminRequest) GetOperation() EntityOperation {
	if m != nil {
		return m.Operation
	}
	return EntityOperation_ADD_OR_UPDATE
}

type CorporationAdminRequest struct {
	Corporation *Corporation    `protobuf:"bytes,1,opt,name=Corporation" json:"Corporation,omitempty"`
	Operation   EntityOperation `protobuf:"varint,2,opt,name=Operation,enum=abaeve.auth.EntityOperation" json:"Operation,omitempty"`
}

func (m *CorporationAdminRequest) Reset()                    { *m = CorporationAdminRequest{} }
func (m *CorporationAdminRequest) String() string            { return proto.CompactTextString(m) }
func (*CorporationAdminRequest) ProtoMessage()               {}
func (*CorporationAdminRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CorporationAdminRequest) GetCorporation() *Corporation {
	if m != nil {
		return m.Corporation
	}
	return nil
}

func (m *CorporationAdminRequest) GetOperation() EntityOperation {
	if m != nil {
		return m.Operation
	}
	return EntityOperation_ADD_OR_UPDATE
}

type CharacterAdminRequest struct {
	Character *Character      `protobuf:"bytes,1,opt,name=Character" json:"Character,omitempty"`
	Operation EntityOperation `protobuf:"varint,2,opt,name=Operation,enum=abaeve.auth.EntityOperation" json:"Operation,omitempty"`
}

func (m *CharacterAdminRequest) Reset()                    { *m = CharacterAdminRequest{} }
func (m *CharacterAdminRequest) String() string            { return proto.CompactTextString(m) }
func (*CharacterAdminRequest) ProtoMessage()               {}
func (*CharacterAdminRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CharacterAdminRequest) GetCharacter() *Character {
	if m != nil {
		return m.Character
	}
	return nil
}

func (m *CharacterAdminRequest) GetOperation() EntityOperation {
	if m != nil {
		return m.Operation
	}
	return EntityOperation_ADD_OR_UPDATE
}

type EntityQueryRequest struct {
	EntityType EntityType `protobuf:"varint,1,opt,name=EntityType,enum=abaeve.auth.EntityType" json:"EntityType,omitempty"`
}

func (m *EntityQueryRequest) Reset()                    { *m = EntityQueryRequest{} }
func (m *EntityQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*EntityQueryRequest) ProtoMessage()               {}
func (*EntityQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *EntityQueryRequest) GetEntityType() EntityType {
	if m != nil {
		return m.EntityType
	}
	return EntityType_ALLIANCE
}

func init() {
	proto.RegisterType((*AuthCreateRequest)(nil), "abaeve.auth.AuthCreateRequest")
	proto.RegisterType((*AuthCreateResponse)(nil), "abaeve.auth.AuthCreateResponse")
	proto.RegisterType((*AuthConfirmRequest)(nil), "abaeve.auth.AuthConfirmRequest")
	proto.RegisterType((*AuthConfirmResponse)(nil), "abaeve.auth.AuthConfirmResponse")
	proto.RegisterType((*CharactersResponse)(nil), "abaeve.auth.CharactersResponse")
	proto.RegisterType((*Character)(nil), "abaeve.auth.Character")
	proto.RegisterType((*CorporationsResponse)(nil), "abaeve.auth.CorporationsResponse")
	proto.RegisterType((*Corporation)(nil), "abaeve.auth.Corporation")
	proto.RegisterType((*AlliancesResponse)(nil), "abaeve.auth.AlliancesResponse")
	proto.RegisterType((*Alliance)(nil), "abaeve.auth.Alliance")
	proto.RegisterType((*EntityAdminResponse)(nil), "abaeve.auth.EntityAdminResponse")
	proto.RegisterType((*AllianceAdminRequest)(nil), "abaeve.auth.AllianceAdminRequest")
	proto.RegisterType((*CorporationAdminRequest)(nil), "abaeve.auth.CorporationAdminRequest")
	proto.RegisterType((*CharacterAdminRequest)(nil), "abaeve.auth.CharacterAdminRequest")
	proto.RegisterType((*EntityQueryRequest)(nil), "abaeve.auth.EntityQueryRequest")
	proto.RegisterEnum("abaeve.auth.EntityType", EntityType_name, EntityType_value)
	proto.RegisterEnum("abaeve.auth.EntityOperation", EntityOperation_name, EntityOperation_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserAuthentication service

type UserAuthenticationClient interface {
	// Called by the auth-web to state someone has started the auth process
	Create(ctx context.Context, in *AuthCreateRequest, opts ...client.CallOption) (*AuthCreateResponse, error)
	// Called by the auth-bot or another system to state that they've linked a character to their account
	Confirm(ctx context.Context, in *AuthConfirmRequest, opts ...client.CallOption) (*AuthConfirmResponse, error)
}

type userAuthenticationClient struct {
	c           client.Client
	serviceName string
}

func NewUserAuthenticationClient(serviceName string, c client.Client) UserAuthenticationClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "abaeve.auth"
	}
	return &userAuthenticationClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userAuthenticationClient) Create(ctx context.Context, in *AuthCreateRequest, opts ...client.CallOption) (*AuthCreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthentication.Create", in)
	out := new(AuthCreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthenticationClient) Confirm(ctx context.Context, in *AuthConfirmRequest, opts ...client.CallOption) (*AuthConfirmResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthentication.Confirm", in)
	out := new(AuthConfirmResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserAuthentication service

type UserAuthenticationHandler interface {
	// Called by the auth-web to state someone has started the auth process
	Create(context.Context, *AuthCreateRequest, *AuthCreateResponse) error
	// Called by the auth-bot or another system to state that they've linked a character to their account
	Confirm(context.Context, *AuthConfirmRequest, *AuthConfirmResponse) error
}

func RegisterUserAuthenticationHandler(s server.Server, hdlr UserAuthenticationHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserAuthentication{hdlr}, opts...))
}

type UserAuthentication struct {
	UserAuthenticationHandler
}

func (h *UserAuthentication) Create(ctx context.Context, in *AuthCreateRequest, out *AuthCreateResponse) error {
	return h.UserAuthenticationHandler.Create(ctx, in, out)
}

func (h *UserAuthentication) Confirm(ctx context.Context, in *AuthConfirmRequest, out *AuthConfirmResponse) error {
	return h.UserAuthenticationHandler.Confirm(ctx, in, out)
}

// Client API for EntityQuery service

type EntityQueryClient interface {
	GetAlliances(ctx context.Context, in *EntityQueryRequest, opts ...client.CallOption) (*AlliancesResponse, error)
	GetCorporations(ctx context.Context, in *EntityQueryRequest, opts ...client.CallOption) (*CorporationsResponse, error)
	GetCharacters(ctx context.Context, in *EntityQueryRequest, opts ...client.CallOption) (*CharactersResponse, error)
}

type entityQueryClient struct {
	c           client.Client
	serviceName string
}

func NewEntityQueryClient(serviceName string, c client.Client) EntityQueryClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "abaeve.auth"
	}
	return &entityQueryClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *entityQueryClient) GetAlliances(ctx context.Context, in *EntityQueryRequest, opts ...client.CallOption) (*AlliancesResponse, error) {
	req := c.c.NewRequest(c.serviceName, "EntityQuery.GetAlliances", in)
	out := new(AlliancesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityQueryClient) GetCorporations(ctx context.Context, in *EntityQueryRequest, opts ...client.CallOption) (*CorporationsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "EntityQuery.GetCorporations", in)
	out := new(CorporationsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityQueryClient) GetCharacters(ctx context.Context, in *EntityQueryRequest, opts ...client.CallOption) (*CharactersResponse, error) {
	req := c.c.NewRequest(c.serviceName, "EntityQuery.GetCharacters", in)
	out := new(CharactersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EntityQuery service

type EntityQueryHandler interface {
	GetAlliances(context.Context, *EntityQueryRequest, *AlliancesResponse) error
	GetCorporations(context.Context, *EntityQueryRequest, *CorporationsResponse) error
	GetCharacters(context.Context, *EntityQueryRequest, *CharactersResponse) error
}

func RegisterEntityQueryHandler(s server.Server, hdlr EntityQueryHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&EntityQuery{hdlr}, opts...))
}

type EntityQuery struct {
	EntityQueryHandler
}

func (h *EntityQuery) GetAlliances(ctx context.Context, in *EntityQueryRequest, out *AlliancesResponse) error {
	return h.EntityQueryHandler.GetAlliances(ctx, in, out)
}

func (h *EntityQuery) GetCorporations(ctx context.Context, in *EntityQueryRequest, out *CorporationsResponse) error {
	return h.EntityQueryHandler.GetCorporations(ctx, in, out)
}

func (h *EntityQuery) GetCharacters(ctx context.Context, in *EntityQueryRequest, out *CharactersResponse) error {
	return h.EntityQueryHandler.GetCharacters(ctx, in, out)
}

// Client API for EntityAdmin service

type EntityAdminClient interface {
	AllianceUpdate(ctx context.Context, in *AllianceAdminRequest, opts ...client.CallOption) (*EntityAdminResponse, error)
	CorporationUpdate(ctx context.Context, in *CorporationAdminRequest, opts ...client.CallOption) (*EntityAdminResponse, error)
	CharacterUpdate(ctx context.Context, in *CharacterAdminRequest, opts ...client.CallOption) (*EntityAdminResponse, error)
}

type entityAdminClient struct {
	c           client.Client
	serviceName string
}

func NewEntityAdminClient(serviceName string, c client.Client) EntityAdminClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "abaeve.auth"
	}
	return &entityAdminClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *entityAdminClient) AllianceUpdate(ctx context.Context, in *AllianceAdminRequest, opts ...client.CallOption) (*EntityAdminResponse, error) {
	req := c.c.NewRequest(c.serviceName, "EntityAdmin.AllianceUpdate", in)
	out := new(EntityAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityAdminClient) CorporationUpdate(ctx context.Context, in *CorporationAdminRequest, opts ...client.CallOption) (*EntityAdminResponse, error) {
	req := c.c.NewRequest(c.serviceName, "EntityAdmin.CorporationUpdate", in)
	out := new(EntityAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityAdminClient) CharacterUpdate(ctx context.Context, in *CharacterAdminRequest, opts ...client.CallOption) (*EntityAdminResponse, error) {
	req := c.c.NewRequest(c.serviceName, "EntityAdmin.CharacterUpdate", in)
	out := new(EntityAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EntityAdmin service

type EntityAdminHandler interface {
	AllianceUpdate(context.Context, *AllianceAdminRequest, *EntityAdminResponse) error
	CorporationUpdate(context.Context, *CorporationAdminRequest, *EntityAdminResponse) error
	CharacterUpdate(context.Context, *CharacterAdminRequest, *EntityAdminResponse) error
}

func RegisterEntityAdminHandler(s server.Server, hdlr EntityAdminHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&EntityAdmin{hdlr}, opts...))
}

type EntityAdmin struct {
	EntityAdminHandler
}

func (h *EntityAdmin) AllianceUpdate(ctx context.Context, in *AllianceAdminRequest, out *EntityAdminResponse) error {
	return h.EntityAdminHandler.AllianceUpdate(ctx, in, out)
}

func (h *EntityAdmin) CorporationUpdate(ctx context.Context, in *CorporationAdminRequest, out *EntityAdminResponse) error {
	return h.EntityAdminHandler.CorporationUpdate(ctx, in, out)
}

func (h *EntityAdmin) CharacterUpdate(ctx context.Context, in *CharacterAdminRequest, out *EntityAdminResponse) error {
	return h.EntityAdminHandler.CharacterUpdate(ctx, in, out)
}

func init() { proto.RegisterFile("auth-srv.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 781 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x4e, 0x13, 0x41,
	0x14, 0x66, 0xdb, 0x52, 0xda, 0x53, 0xfa, 0x77, 0xf8, 0xdb, 0x10, 0x02, 0x65, 0xc3, 0x05, 0x12,
	0xad, 0x5a, 0x4d, 0x4c, 0xb8, 0x30, 0x6e, 0xb6, 0x15, 0x1b, 0x4b, 0x0b, 0x43, 0x2b, 0x31, 0x51,
	0xc9, 0xd2, 0x8e, 0x61, 0x03, 0xec, 0xd6, 0xdd, 0x2d, 0x09, 0x0f, 0xe0, 0x85, 0x37, 0x26, 0xbe,
	0x81, 0xaf, 0xe0, 0x7b, 0xf9, 0x10, 0x66, 0xff, 0x67, 0xea, 0xae, 0x80, 0xdc, 0x75, 0xce, 0xcf,
	0x37, 0xdf, 0x99, 0xf3, 0x9d, 0xd3, 0x85, 0x92, 0x3a, 0xb1, 0xcf, 0x1e, 0x59, 0xe6, 0x55, 0x7d,
	0x6c, 0x1a, 0xb6, 0x81, 0x05, 0xf5, 0x54, 0xa5, 0x57, 0xb4, 0xee, 0x98, 0xa5, 0xdf, 0x02, 0x54,
	0xe5, 0x89, 0x7d, 0xa6, 0x98, 0x54, 0xb5, 0x29, 0xa1, 0x5f, 0x26, 0xd4, 0xb2, 0x71, 0x11, 0x66,
	0xfb, 0xc6, 0x39, 0xd5, 0x45, 0xa1, 0x26, 0x6c, 0xe7, 0x89, 0x77, 0xc0, 0xe7, 0x90, 0x57, 0xce,
	0x54, 0x53, 0x1d, 0xda, 0xd4, 0x14, 0x53, 0x35, 0x61, 0xbb, 0xd0, 0x58, 0xae, 0x33, 0x60, 0xf5,
	0xd0, 0x4b, 0xa2, 0x40, 0xdc, 0x85, 0x82, 0x62, 0x98, 0x63, 0xc3, 0x54, 0x6d, 0xcd, 0xd0, 0xc5,
	0xb4, 0x9b, 0x27, 0xf2, 0x79, 0x91, 0x9f, 0xb0, 0xc1, 0xf8, 0x14, 0x72, 0xf2, 0xc5, 0x85, 0xa6,
	0xea, 0x43, 0x2a, 0x66, 0xdc, 0xc4, 0x25, 0x2e, 0x31, 0x70, 0x92, 0x30, 0x0c, 0xd7, 0x20, 0xef,
	0xd4, 0x73, 0x34, 0x34, 0xc6, 0x54, 0x9c, 0xad, 0xa5, 0xb7, 0xf3, 0x24, 0x32, 0x48, 0x9f, 0x00,
	0xd9, 0x6a, 0xad, 0xb1, 0xa1, 0x5b, 0x14, 0xeb, 0x9e, 0x95, 0xea, 0xb6, 0x36, 0x74, 0x2f, 0x56,
	0x8c, 0x11, 0xf5, 0x6b, 0x8f, 0xf1, 0xa0, 0x08, 0x73, 0x47, 0x93, 0xe1, 0x90, 0x5a, 0x96, 0xfb,
	0x0c, 0x39, 0x12, 0x1c, 0xa5, 0x0f, 0x3e, 0xbe, 0xa1, 0x7f, 0xd6, 0xcc, 0xcb, 0xe0, 0x39, 0x97,
	0x21, 0x3b, 0xb0, 0xa8, 0xd9, 0x1e, 0xf9, 0x98, 0xfe, 0x29, 0xe1, 0xde, 0x54, 0xd2, 0xbd, 0xd2,
	0x00, 0x16, 0x38, 0x74, 0x9f, 0x3e, 0x43, 0x47, 0xe0, 0xe8, 0xe0, 0x16, 0x14, 0xc3, 0x46, 0x74,
	0xd5, 0xcb, 0x00, 0x9b, 0x37, 0x4a, 0xaf, 0x00, 0x43, 0x83, 0x15, 0xa2, 0xee, 0x40, 0xa6, 0xa3,
	0x59, 0xb6, 0x28, 0xd4, 0xd2, 0xff, 0x68, 0xb4, 0x1b, 0x23, 0x0d, 0x18, 0x65, 0x60, 0x09, 0x52,
	0x7e, 0xa5, 0x69, 0x92, 0x6a, 0x8f, 0x10, 0x21, 0xc3, 0xdc, 0xed, 0xfe, 0x76, 0x89, 0x45, 0x7d,
	0x6e, 0x8f, 0x5c, 0x59, 0xa4, 0x09, 0x6f, 0x94, 0x9a, 0xb0, 0xc8, 0x18, 0x22, 0x6a, 0x0f, 0x39,
	0x6a, 0xc9, 0x5a, 0xf2, 0xc8, 0x69, 0x9c, 0x00, 0x6f, 0x45, 0x6f, 0x19, 0xb2, 0x7d, 0x6d, 0x78,
	0x4e, 0x4d, 0x97, 0x57, 0x9e, 0xf8, 0x27, 0x5c, 0x07, 0x08, 0x84, 0xd6, 0x1e, 0xb9, 0x8a, 0x4c,
	0x13, 0xc6, 0x22, 0xbd, 0x84, 0x6a, 0x70, 0x8a, 0xd8, 0x3e, 0xe0, 0xd8, 0x26, 0x08, 0xd8, 0xa3,
	0xfa, 0x3a, 0xd2, 0xfb, 0x7d, 0x78, 0x4a, 0x8f, 0x61, 0xa1, 0xa5, 0xdb, 0x9a, 0x7d, 0x2d, 0x8f,
	0x2e, 0x35, 0xfd, 0x66, 0xa1, 0x48, 0x5f, 0x05, 0x58, 0x0c, 0x6e, 0xf6, 0x73, 0x3c, 0xe9, 0xb2,
	0x13, 0x28, 0xdc, 0x6e, 0x02, 0x77, 0x21, 0xdf, 0x1b, 0x53, 0x7f, 0xdc, 0x1d, 0xb6, 0xa5, 0xc6,
	0x1a, 0x97, 0xe3, 0x51, 0x0b, 0x63, 0x48, 0x14, 0x2e, 0xfd, 0x10, 0x60, 0x85, 0x69, 0x16, 0x47,
	0x65, 0x6a, 0x91, 0x08, 0x77, 0x59, 0x24, 0xf7, 0xe1, 0xf4, 0x4d, 0x80, 0xa5, 0x50, 0xdd, 0x1c,
	0x23, 0x6e, 0x21, 0x0a, 0xb7, 0x5f, 0x88, 0xff, 0xcf, 0x65, 0x1f, 0xd0, 0xf3, 0x1e, 0x4e, 0xa8,
	0x79, 0x1d, 0xf0, 0x78, 0x01, 0xe0, 0x59, 0xfb, 0xd7, 0x63, 0xaf, 0x4d, 0xa5, 0xc6, 0x4a, 0x0c,
	0xa4, 0xe3, 0x26, 0x4c, 0xe8, 0x4e, 0x93, 0x4d, 0xc4, 0x79, 0xc8, 0xc9, 0x9d, 0x4e, 0x5b, 0xee,
	0x2a, 0xad, 0xca, 0x0c, 0x96, 0xa1, 0xa0, 0xf4, 0xc8, 0x41, 0x8f, 0xc8, 0xfd, 0x76, 0xaf, 0x5b,
	0x11, 0xb0, 0x08, 0x79, 0xe5, 0x8d, 0x4c, 0x64, 0xa5, 0xdf, 0x22, 0x95, 0x14, 0xe6, 0x20, 0x43,
	0x7a, 0x9d, 0x56, 0x25, 0xbd, 0xf3, 0x04, 0xca, 0x53, 0x94, 0xb1, 0x0a, 0x45, 0xb9, 0xd9, 0x3c,
	0xe9, 0x91, 0x93, 0xc1, 0x41, 0x53, 0xee, 0x3b, 0x78, 0x00, 0x59, 0xd2, 0xda, 0xef, 0xbd, 0x6b,
	0x55, 0x84, 0xc6, 0x2f, 0x01, 0xd0, 0xd9, 0x81, 0xfc, 0x8e, 0xc3, 0xb7, 0x90, 0xf5, 0x36, 0x33,
	0xae, 0xf3, 0x22, 0x9b, 0xfe, 0x83, 0x5a, 0xdd, 0x48, 0xf4, 0x7b, 0x52, 0x97, 0x66, 0xb0, 0x0b,
	0x73, 0xfe, 0xa2, 0xc4, 0x98, 0x68, 0x6e, 0x41, 0xaf, 0xd6, 0x92, 0x03, 0x02, 0xbc, 0xc6, 0xf7,
	0x14, 0x14, 0x98, 0xb7, 0xc7, 0x43, 0x98, 0xdf, 0xa3, 0x76, 0x38, 0xee, 0x53, 0x97, 0xfc, 0xdd,
	0xa5, 0xd5, 0xf5, 0xd8, 0xc1, 0xb1, 0x18, 0xca, 0xc7, 0x50, 0xde, 0xa3, 0x36, 0xbb, 0xf2, 0x6e,
	0x46, 0xdd, 0x4c, 0x1a, 0x00, 0x16, 0xf8, 0x08, 0x8a, 0x0e, 0x70, 0xb8, 0xe4, 0x6f, 0x86, 0xdd,
	0x88, 0xd7, 0x31, 0x03, 0xda, 0xf8, 0x19, 0x3e, 0x88, 0x3b, 0x14, 0x78, 0x0c, 0xa5, 0xa0, 0xa8,
	0xc1, 0x78, 0xe4, 0x74, 0x71, 0x33, 0xb6, 0x62, 0x76, 0x84, 0xa6, 0x5e, 0x3e, 0x66, 0x69, 0x49,
	0x33, 0xf8, 0x11, 0xaa, 0x4c, 0x5d, 0x3e, 0xf6, 0x56, 0x52, 0xdd, 0x77, 0x86, 0x7f, 0x0f, 0xe5,
	0xb0, 0x3e, 0x1f, 0x5c, 0x8a, 0xaf, 0xfe, 0xae, 0xd0, 0xa7, 0x59, 0xf7, 0x8b, 0xeb, 0xd9, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x15, 0xfa, 0x60, 0x52, 0x83, 0x09, 0x00, 0x00,
}
