// Code generated by protoc-gen-go.
// source: auth-srv.proto
// DO NOT EDIT!

/*
Package abaeve_auth is a generated protocol buffer package.

It is generated from these files:
	auth-srv.proto

It has these top-level messages:
	AuthCreateRequest
	AuthCreateResponse
	AuthConfirmRequest
	AuthConfirmResponse
	GetRolesRequest
	AuthAdminRequest
	AuthAdminResponse
	Character
	Corporation
	Alliance
*/
package abaeve_auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EntityType int32

const (
	EntityType_ALLIANCE    EntityType = 0
	EntityType_CORPORATION EntityType = 1
	EntityType_CHARACTER   EntityType = 2
)

var EntityType_name = map[int32]string{
	0: "ALLIANCE",
	1: "CORPORATION",
	2: "CHARACTER",
}
var EntityType_value = map[string]int32{
	"ALLIANCE":    0,
	"CORPORATION": 1,
	"CHARACTER":   2,
}

func (x EntityType) String() string {
	return proto.EnumName(EntityType_name, int32(x))
}
func (EntityType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AuthCreateRequest struct {
	Token       string       `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	Character   *Character   `protobuf:"bytes,2,opt,name=Character" json:"Character,omitempty"`
	Corporation *Corporation `protobuf:"bytes,3,opt,name=Corporation" json:"Corporation,omitempty"`
	Alliance    *Alliance    `protobuf:"bytes,4,opt,name=Alliance" json:"Alliance,omitempty"`
	AuthScope   []string     `protobuf:"bytes,5,rep,name=AuthScope" json:"AuthScope,omitempty"`
}

func (m *AuthCreateRequest) Reset()                    { *m = AuthCreateRequest{} }
func (m *AuthCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthCreateRequest) ProtoMessage()               {}
func (*AuthCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthCreateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthCreateRequest) GetCharacter() *Character {
	if m != nil {
		return m.Character
	}
	return nil
}

func (m *AuthCreateRequest) GetCorporation() *Corporation {
	if m != nil {
		return m.Corporation
	}
	return nil
}

func (m *AuthCreateRequest) GetAlliance() *Alliance {
	if m != nil {
		return m.Alliance
	}
	return nil
}

func (m *AuthCreateRequest) GetAuthScope() []string {
	if m != nil {
		return m.AuthScope
	}
	return nil
}

type AuthCreateResponse struct {
	AuthenticationCode string `protobuf:"bytes,1,opt,name=AuthenticationCode" json:"AuthenticationCode,omitempty"`
	Success            bool   `protobuf:"varint,2,opt,name=Success" json:"Success,omitempty"`
}

func (m *AuthCreateResponse) Reset()                    { *m = AuthCreateResponse{} }
func (m *AuthCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthCreateResponse) ProtoMessage()               {}
func (*AuthCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthCreateResponse) GetAuthenticationCode() string {
	if m != nil {
		return m.AuthenticationCode
	}
	return ""
}

func (m *AuthCreateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AuthConfirmRequest struct {
	UserId             string `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
	AuthenticationCode string `protobuf:"bytes,2,opt,name=AuthenticationCode" json:"AuthenticationCode,omitempty"`
}

func (m *AuthConfirmRequest) Reset()                    { *m = AuthConfirmRequest{} }
func (m *AuthConfirmRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthConfirmRequest) ProtoMessage()               {}
func (*AuthConfirmRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthConfirmRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AuthConfirmRequest) GetAuthenticationCode() string {
	if m != nil {
		return m.AuthenticationCode
	}
	return ""
}

type AuthConfirmResponse struct {
	Success       bool     `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	CharacterName string   `protobuf:"bytes,2,opt,name=CharacterName" json:"CharacterName,omitempty"`
	Roles         []string `protobuf:"bytes,3,rep,name=Roles" json:"Roles,omitempty"`
}

func (m *AuthConfirmResponse) Reset()                    { *m = AuthConfirmResponse{} }
func (m *AuthConfirmResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthConfirmResponse) ProtoMessage()               {}
func (*AuthConfirmResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AuthConfirmResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AuthConfirmResponse) GetCharacterName() string {
	if m != nil {
		return m.CharacterName
	}
	return ""
}

func (m *AuthConfirmResponse) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type GetRolesRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
}

func (m *GetRolesRequest) Reset()                    { *m = GetRolesRequest{} }
func (m *GetRolesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRolesRequest) ProtoMessage()               {}
func (*GetRolesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetRolesRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type AuthAdminRequest struct {
	EntityId     []int64      `protobuf:"varint,1,rep,packed,name=EntityId" json:"EntityId,omitempty"`
	EntityName   []string     `protobuf:"bytes,2,rep,name=EntityName" json:"EntityName,omitempty"`
	EntityTicker []string     `protobuf:"bytes,3,rep,name=EntityTicker" json:"EntityTicker,omitempty"`
	EntityType   []EntityType `protobuf:"varint,4,rep,packed,name=EntityType,enum=abaeve.auth.EntityType" json:"EntityType,omitempty"`
	Role         string       `protobuf:"bytes,5,opt,name=Role" json:"Role,omitempty"`
}

func (m *AuthAdminRequest) Reset()                    { *m = AuthAdminRequest{} }
func (m *AuthAdminRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthAdminRequest) ProtoMessage()               {}
func (*AuthAdminRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AuthAdminRequest) GetEntityId() []int64 {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *AuthAdminRequest) GetEntityName() []string {
	if m != nil {
		return m.EntityName
	}
	return nil
}

func (m *AuthAdminRequest) GetEntityTicker() []string {
	if m != nil {
		return m.EntityTicker
	}
	return nil
}

func (m *AuthAdminRequest) GetEntityType() []EntityType {
	if m != nil {
		return m.EntityType
	}
	return nil
}

func (m *AuthAdminRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type AuthAdminResponse struct {
	EntityId   []int64      `protobuf:"varint,1,rep,packed,name=EntityId" json:"EntityId,omitempty"`
	EntityName []string     `protobuf:"bytes,2,rep,name=EntityName" json:"EntityName,omitempty"`
	EntityType []EntityType `protobuf:"varint,3,rep,packed,name=EntityType,enum=abaeve.auth.EntityType" json:"EntityType,omitempty"`
	Success    bool         `protobuf:"varint,4,opt,name=Success" json:"Success,omitempty"`
}

func (m *AuthAdminResponse) Reset()                    { *m = AuthAdminResponse{} }
func (m *AuthAdminResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthAdminResponse) ProtoMessage()               {}
func (*AuthAdminResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AuthAdminResponse) GetEntityId() []int64 {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *AuthAdminResponse) GetEntityName() []string {
	if m != nil {
		return m.EntityName
	}
	return nil
}

func (m *AuthAdminResponse) GetEntityType() []EntityType {
	if m != nil {
		return m.EntityType
	}
	return nil
}

func (m *AuthAdminResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Character struct {
	Id   int64  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
}

func (m *Character) Reset()                    { *m = Character{} }
func (m *Character) String() string            { return proto.CompactTextString(m) }
func (*Character) ProtoMessage()               {}
func (*Character) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Character) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Character) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Corporation struct {
	Id     int64  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Ticker string `protobuf:"bytes,3,opt,name=Ticker" json:"Ticker,omitempty"`
}

func (m *Corporation) Reset()                    { *m = Corporation{} }
func (m *Corporation) String() string            { return proto.CompactTextString(m) }
func (*Corporation) ProtoMessage()               {}
func (*Corporation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Corporation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Corporation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Corporation) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

type Alliance struct {
	Id     int64  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Ticker string `protobuf:"bytes,3,opt,name=Ticker" json:"Ticker,omitempty"`
}

func (m *Alliance) Reset()                    { *m = Alliance{} }
func (m *Alliance) String() string            { return proto.CompactTextString(m) }
func (*Alliance) ProtoMessage()               {}
func (*Alliance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Alliance) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Alliance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Alliance) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthCreateRequest)(nil), "abaeve.auth.AuthCreateRequest")
	proto.RegisterType((*AuthCreateResponse)(nil), "abaeve.auth.AuthCreateResponse")
	proto.RegisterType((*AuthConfirmRequest)(nil), "abaeve.auth.AuthConfirmRequest")
	proto.RegisterType((*AuthConfirmResponse)(nil), "abaeve.auth.AuthConfirmResponse")
	proto.RegisterType((*GetRolesRequest)(nil), "abaeve.auth.GetRolesRequest")
	proto.RegisterType((*AuthAdminRequest)(nil), "abaeve.auth.AuthAdminRequest")
	proto.RegisterType((*AuthAdminResponse)(nil), "abaeve.auth.AuthAdminResponse")
	proto.RegisterType((*Character)(nil), "abaeve.auth.Character")
	proto.RegisterType((*Corporation)(nil), "abaeve.auth.Corporation")
	proto.RegisterType((*Alliance)(nil), "abaeve.auth.Alliance")
	proto.RegisterEnum("abaeve.auth.EntityType", EntityType_name, EntityType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Publisher API

type Publisher interface {
	Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error
}

type publisher struct {
	c     client.Client
	topic string
}

func (p *publisher) Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error {
	return p.c.Publish(ctx, p.c.NewPublication(p.topic, msg), opts...)
}

func NewPublisher(topic string, c client.Client) Publisher {
	if c == nil {
		c = client.NewClient()
	}
	return &publisher{c, topic}
}

// Subscriber API

func RegisterSubscriber(topic string, s server.Server, h interface{}, opts ...server.SubscriberOption) error {
	return s.Subscribe(s.NewSubscriber(topic, h, opts...))
}

// Client API for UserAuthentication service

type UserAuthenticationClient interface {
	// Called by the auth-web to state someone has started the auth process
	Create(ctx context.Context, in *AuthCreateRequest, opts ...client.CallOption) (*AuthCreateResponse, error)
	// Called by the auth-bot or another system to state that they've linked a character to their account
	Confirm(ctx context.Context, in *AuthConfirmRequest, opts ...client.CallOption) (*AuthConfirmResponse, error)
	// Called to get all roles for an already authed user
	GetRoles(ctx context.Context, in *GetRolesRequest, opts ...client.CallOption) (*AuthConfirmResponse, error)
}

type userAuthenticationClient struct {
	c           client.Client
	serviceName string
}

func NewUserAuthenticationClient(serviceName string, c client.Client) UserAuthenticationClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "abaeve.auth"
	}
	return &userAuthenticationClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userAuthenticationClient) Create(ctx context.Context, in *AuthCreateRequest, opts ...client.CallOption) (*AuthCreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthentication.Create", in)
	out := new(AuthCreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthenticationClient) Confirm(ctx context.Context, in *AuthConfirmRequest, opts ...client.CallOption) (*AuthConfirmResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthentication.Confirm", in)
	out := new(AuthConfirmResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthenticationClient) GetRoles(ctx context.Context, in *GetRolesRequest, opts ...client.CallOption) (*AuthConfirmResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthentication.GetRoles", in)
	out := new(AuthConfirmResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserAuthentication service

type UserAuthenticationHandler interface {
	// Called by the auth-web to state someone has started the auth process
	Create(context.Context, *AuthCreateRequest, *AuthCreateResponse) error
	// Called by the auth-bot or another system to state that they've linked a character to their account
	Confirm(context.Context, *AuthConfirmRequest, *AuthConfirmResponse) error
	// Called to get all roles for an already authed user
	GetRoles(context.Context, *GetRolesRequest, *AuthConfirmResponse) error
}

func RegisterUserAuthenticationHandler(s server.Server, hdlr UserAuthenticationHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserAuthentication{hdlr}, opts...))
}

type UserAuthentication struct {
	UserAuthenticationHandler
}

func (h *UserAuthentication) Create(ctx context.Context, in *AuthCreateRequest, out *AuthCreateResponse) error {
	return h.UserAuthenticationHandler.Create(ctx, in, out)
}

func (h *UserAuthentication) Confirm(ctx context.Context, in *AuthConfirmRequest, out *AuthConfirmResponse) error {
	return h.UserAuthenticationHandler.Confirm(ctx, in, out)
}

func (h *UserAuthentication) GetRoles(ctx context.Context, in *GetRolesRequest, out *AuthConfirmResponse) error {
	return h.UserAuthenticationHandler.GetRoles(ctx, in, out)
}

// Client API for UserAuthenticationAdmin service

type UserAuthenticationAdminClient interface {
	CharacterRoleAdd(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error)
	CharacterRoleRemove(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error)
	CorporationAllianceRoleAdd(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error)
	CorporationAllianceRoleRemove(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error)
	CorporationRoleAdd(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error)
	CorporationRoleRemove(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error)
	AllianceRoleAdd(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error)
	AllianceRoleRemove(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error)
	AllianceCharacterLeadershipRoleAdd(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error)
	AllianceCharacterLeadershipRoleRemove(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error)
	CorporationCharacterLeadershipRoleAdd(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error)
	CorporationCharacterLeadershipRoleRemove(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error)
}

type userAuthenticationAdminClient struct {
	c           client.Client
	serviceName string
}

func NewUserAuthenticationAdminClient(serviceName string, c client.Client) UserAuthenticationAdminClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "abaeve.auth"
	}
	return &userAuthenticationAdminClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userAuthenticationAdminClient) CharacterRoleAdd(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthenticationAdmin.CharacterRoleAdd", in)
	out := new(AuthAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthenticationAdminClient) CharacterRoleRemove(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthenticationAdmin.CharacterRoleRemove", in)
	out := new(AuthAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthenticationAdminClient) CorporationAllianceRoleAdd(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthenticationAdmin.CorporationAllianceRoleAdd", in)
	out := new(AuthAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthenticationAdminClient) CorporationAllianceRoleRemove(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthenticationAdmin.CorporationAllianceRoleRemove", in)
	out := new(AuthAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthenticationAdminClient) CorporationRoleAdd(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthenticationAdmin.CorporationRoleAdd", in)
	out := new(AuthAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthenticationAdminClient) CorporationRoleRemove(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthenticationAdmin.CorporationRoleRemove", in)
	out := new(AuthAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthenticationAdminClient) AllianceRoleAdd(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthenticationAdmin.AllianceRoleAdd", in)
	out := new(AuthAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthenticationAdminClient) AllianceRoleRemove(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthenticationAdmin.AllianceRoleRemove", in)
	out := new(AuthAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthenticationAdminClient) AllianceCharacterLeadershipRoleAdd(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthenticationAdmin.AllianceCharacterLeadershipRoleAdd", in)
	out := new(AuthAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthenticationAdminClient) AllianceCharacterLeadershipRoleRemove(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthenticationAdmin.AllianceCharacterLeadershipRoleRemove", in)
	out := new(AuthAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthenticationAdminClient) CorporationCharacterLeadershipRoleAdd(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthenticationAdmin.CorporationCharacterLeadershipRoleAdd", in)
	out := new(AuthAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthenticationAdminClient) CorporationCharacterLeadershipRoleRemove(ctx context.Context, in *AuthAdminRequest, opts ...client.CallOption) (*AuthAdminResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserAuthenticationAdmin.CorporationCharacterLeadershipRoleRemove", in)
	out := new(AuthAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserAuthenticationAdmin service

type UserAuthenticationAdminHandler interface {
	CharacterRoleAdd(context.Context, *AuthAdminRequest, *AuthAdminResponse) error
	CharacterRoleRemove(context.Context, *AuthAdminRequest, *AuthAdminResponse) error
	CorporationAllianceRoleAdd(context.Context, *AuthAdminRequest, *AuthAdminResponse) error
	CorporationAllianceRoleRemove(context.Context, *AuthAdminRequest, *AuthAdminResponse) error
	CorporationRoleAdd(context.Context, *AuthAdminRequest, *AuthAdminResponse) error
	CorporationRoleRemove(context.Context, *AuthAdminRequest, *AuthAdminResponse) error
	AllianceRoleAdd(context.Context, *AuthAdminRequest, *AuthAdminResponse) error
	AllianceRoleRemove(context.Context, *AuthAdminRequest, *AuthAdminResponse) error
	AllianceCharacterLeadershipRoleAdd(context.Context, *AuthAdminRequest, *AuthAdminResponse) error
	AllianceCharacterLeadershipRoleRemove(context.Context, *AuthAdminRequest, *AuthAdminResponse) error
	CorporationCharacterLeadershipRoleAdd(context.Context, *AuthAdminRequest, *AuthAdminResponse) error
	CorporationCharacterLeadershipRoleRemove(context.Context, *AuthAdminRequest, *AuthAdminResponse) error
}

func RegisterUserAuthenticationAdminHandler(s server.Server, hdlr UserAuthenticationAdminHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserAuthenticationAdmin{hdlr}, opts...))
}

type UserAuthenticationAdmin struct {
	UserAuthenticationAdminHandler
}

func (h *UserAuthenticationAdmin) CharacterRoleAdd(ctx context.Context, in *AuthAdminRequest, out *AuthAdminResponse) error {
	return h.UserAuthenticationAdminHandler.CharacterRoleAdd(ctx, in, out)
}

func (h *UserAuthenticationAdmin) CharacterRoleRemove(ctx context.Context, in *AuthAdminRequest, out *AuthAdminResponse) error {
	return h.UserAuthenticationAdminHandler.CharacterRoleRemove(ctx, in, out)
}

func (h *UserAuthenticationAdmin) CorporationAllianceRoleAdd(ctx context.Context, in *AuthAdminRequest, out *AuthAdminResponse) error {
	return h.UserAuthenticationAdminHandler.CorporationAllianceRoleAdd(ctx, in, out)
}

func (h *UserAuthenticationAdmin) CorporationAllianceRoleRemove(ctx context.Context, in *AuthAdminRequest, out *AuthAdminResponse) error {
	return h.UserAuthenticationAdminHandler.CorporationAllianceRoleRemove(ctx, in, out)
}

func (h *UserAuthenticationAdmin) CorporationRoleAdd(ctx context.Context, in *AuthAdminRequest, out *AuthAdminResponse) error {
	return h.UserAuthenticationAdminHandler.CorporationRoleAdd(ctx, in, out)
}

func (h *UserAuthenticationAdmin) CorporationRoleRemove(ctx context.Context, in *AuthAdminRequest, out *AuthAdminResponse) error {
	return h.UserAuthenticationAdminHandler.CorporationRoleRemove(ctx, in, out)
}

func (h *UserAuthenticationAdmin) AllianceRoleAdd(ctx context.Context, in *AuthAdminRequest, out *AuthAdminResponse) error {
	return h.UserAuthenticationAdminHandler.AllianceRoleAdd(ctx, in, out)
}

func (h *UserAuthenticationAdmin) AllianceRoleRemove(ctx context.Context, in *AuthAdminRequest, out *AuthAdminResponse) error {
	return h.UserAuthenticationAdminHandler.AllianceRoleRemove(ctx, in, out)
}

func (h *UserAuthenticationAdmin) AllianceCharacterLeadershipRoleAdd(ctx context.Context, in *AuthAdminRequest, out *AuthAdminResponse) error {
	return h.UserAuthenticationAdminHandler.AllianceCharacterLeadershipRoleAdd(ctx, in, out)
}

func (h *UserAuthenticationAdmin) AllianceCharacterLeadershipRoleRemove(ctx context.Context, in *AuthAdminRequest, out *AuthAdminResponse) error {
	return h.UserAuthenticationAdminHandler.AllianceCharacterLeadershipRoleRemove(ctx, in, out)
}

func (h *UserAuthenticationAdmin) CorporationCharacterLeadershipRoleAdd(ctx context.Context, in *AuthAdminRequest, out *AuthAdminResponse) error {
	return h.UserAuthenticationAdminHandler.CorporationCharacterLeadershipRoleAdd(ctx, in, out)
}

func (h *UserAuthenticationAdmin) CorporationCharacterLeadershipRoleRemove(ctx context.Context, in *AuthAdminRequest, out *AuthAdminResponse) error {
	return h.UserAuthenticationAdminHandler.CorporationCharacterLeadershipRoleRemove(ctx, in, out)
}

func init() { proto.RegisterFile("auth-srv.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xae, 0xe3, 0x1e, 0x92, 0x49, 0x0f, 0xf9, 0xa7, 0x7f, 0x5b, 0x2b, 0x6a, 0x4b, 0x64, 0x51,
	0x29, 0x20, 0x11, 0x44, 0x40, 0x42, 0xea, 0x9d, 0x65, 0x15, 0x88, 0x88, 0x52, 0xb4, 0x4d, 0x11,
	0x17, 0x80, 0x70, 0xed, 0x45, 0xb1, 0x92, 0x78, 0x83, 0xed, 0x54, 0xea, 0x33, 0xf0, 0x16, 0xbc,
	0x08, 0x2f, 0xc4, 0x3b, 0x80, 0xbc, 0x5e, 0x3b, 0xbb, 0x6d, 0xa3, 0x56, 0x8a, 0x7b, 0xe7, 0xd9,
	0x99, 0xfd, 0xe6, 0xfb, 0xe6, 0xb0, 0x09, 0x6c, 0x3a, 0xd3, 0x78, 0xf0, 0x2c, 0x0a, 0x2f, 0x5b,
	0x93, 0x90, 0xc5, 0x0c, 0xab, 0xce, 0x85, 0x43, 0x2f, 0x69, 0x2b, 0x39, 0x36, 0xff, 0x68, 0xf0,
	0x9f, 0x35, 0x8d, 0x07, 0x76, 0x48, 0x9d, 0x98, 0x12, 0xfa, 0x63, 0x4a, 0xa3, 0x18, 0xff, 0x87,
	0x95, 0x3e, 0x1b, 0xd2, 0xc0, 0xd0, 0x1a, 0x5a, 0xb3, 0x42, 0x52, 0x03, 0x5f, 0x41, 0xc5, 0x1e,
	0x38, 0xa1, 0xe3, 0xc6, 0x34, 0x34, 0x4a, 0x0d, 0xad, 0x59, 0x6d, 0xef, 0xb6, 0x24, 0xb0, 0x56,
	0xee, 0x25, 0xb3, 0x40, 0x3c, 0x86, 0xaa, 0xcd, 0xc2, 0x09, 0x0b, 0x9d, 0xd8, 0x67, 0x81, 0xa1,
	0xf3, 0x7b, 0x86, 0x7a, 0x6f, 0xe6, 0x27, 0x72, 0x30, 0xbe, 0x80, 0xb2, 0x35, 0x1a, 0xf9, 0x4e,
	0xe0, 0x52, 0x63, 0x99, 0x5f, 0xdc, 0x51, 0x2e, 0x66, 0x4e, 0x92, 0x87, 0xe1, 0x3e, 0x54, 0x12,
	0x3d, 0x67, 0x2e, 0x9b, 0x50, 0x63, 0xa5, 0xa1, 0x37, 0x2b, 0x64, 0x76, 0x60, 0x7e, 0x05, 0x94,
	0xd5, 0x46, 0x13, 0x16, 0x44, 0x14, 0x5b, 0xe9, 0x29, 0x0d, 0x62, 0xdf, 0xe5, 0x89, 0x6d, 0xe6,
	0x51, 0xa1, 0xfd, 0x16, 0x0f, 0x1a, 0xb0, 0x76, 0x36, 0x75, 0x5d, 0x1a, 0x45, 0xbc, 0x0c, 0x65,
	0x92, 0x99, 0xe6, 0x67, 0x81, 0xcf, 0x82, 0xef, 0x7e, 0x38, 0xce, 0xca, 0xb9, 0x0b, 0xab, 0xe7,
	0x11, 0x0d, 0x3b, 0x9e, 0xc0, 0x14, 0xd6, 0x9c, 0xbc, 0xa5, 0x79, 0x79, 0xcd, 0x21, 0x6c, 0x2b,
	0xe8, 0x82, 0xbe, 0x44, 0x47, 0x53, 0xe8, 0xe0, 0x63, 0xd8, 0xc8, 0x1b, 0xd1, 0x73, 0xc6, 0x19,
	0xb6, 0x7a, 0x98, 0x74, 0x9b, 0xb0, 0x11, 0x8d, 0x0c, 0x9d, 0x97, 0x2b, 0x35, 0xcc, 0x27, 0xb0,
	0xf5, 0x96, 0xc6, 0xfc, 0xfb, 0x0e, 0x1d, 0xe6, 0x6f, 0x0d, 0x6a, 0x09, 0x31, 0xcb, 0x1b, 0xfb,
	0x41, 0x16, 0x5c, 0x87, 0xf2, 0x49, 0x10, 0xfb, 0xf1, 0x15, 0x0f, 0xd7, 0x9b, 0x3a, 0xc9, 0x6d,
	0x3c, 0x04, 0x48, 0xbf, 0x05, 0xa9, 0x24, 0xad, 0x74, 0x82, 0x26, 0xac, 0xa7, 0x56, 0xdf, 0x77,
	0x87, 0x34, 0x14, 0xc4, 0x94, 0x33, 0x7c, 0x9d, 0x61, 0xf4, 0xaf, 0x26, 0xc9, 0x74, 0xe8, 0xcd,
	0xcd, 0xf6, 0x9e, 0x32, 0x1d, 0x33, 0x37, 0x91, 0x42, 0x11, 0x61, 0x39, 0x51, 0x65, 0xac, 0x70,
	0x0d, 0xfc, 0xdb, 0xfc, 0x25, 0xd6, 0x40, 0x28, 0x10, 0x85, 0x5d, 0x44, 0x82, 0x4a, 0x4f, 0xbf,
	0x3f, 0x3d, 0xa9, 0x9b, 0xcb, 0xea, 0x70, 0x3d, 0x97, 0xf6, 0x0f, 0x37, 0xa1, 0x24, 0xfa, 0xa0,
	0x93, 0x52, 0xc7, 0x4b, 0x54, 0x49, 0x1d, 0xe6, 0xdf, 0x66, 0x47, 0x59, 0xbd, 0xfb, 0x5c, 0x49,
	0x5a, 0x9c, 0xd7, 0x9c, 0xb7, 0x38, 0xb5, 0xcc, 0x37, 0xb3, 0x4d, 0x5c, 0x04, 0xe7, 0xe9, 0xb1,
	0x5c, 0x16, 0x5c, 0x87, 0xb2, 0xd5, 0xed, 0x76, 0xac, 0x9e, 0x7d, 0x52, 0x5b, 0xc2, 0x2d, 0xa8,
	0xda, 0xa7, 0xe4, 0xc3, 0x29, 0xb1, 0xfa, 0x9d, 0xd3, 0x5e, 0x4d, 0xc3, 0x0d, 0xa8, 0xd8, 0xef,
	0x2c, 0x62, 0xd9, 0xfd, 0x13, 0x52, 0x2b, 0xb5, 0xff, 0x6a, 0x80, 0xc9, 0xc4, 0xa9, 0x9b, 0x81,
	0xef, 0x61, 0x35, 0xdd, 0x67, 0x3c, 0x54, 0x1f, 0x87, 0xeb, 0xcf, 0x5a, 0xfd, 0xd1, 0x5c, 0x7f,
	0xda, 0x70, 0x73, 0x09, 0x7b, 0xb0, 0x26, 0xd6, 0x0b, 0x6f, 0x89, 0x56, 0xd6, 0xba, 0xde, 0x98,
	0x1f, 0x90, 0xe3, 0x75, 0xa1, 0x9c, 0x6d, 0x11, 0xee, 0x2b, 0xf1, 0xd7, 0x96, 0xeb, 0x3e, 0x68,
	0xed, 0x9f, 0x15, 0xd8, 0xbb, 0x59, 0x01, 0x3e, 0xb4, 0x78, 0x06, 0xb5, 0xd9, 0xfb, 0xcb, 0x46,
	0xd4, 0xf2, 0x3c, 0x3c, 0xb8, 0x81, 0x29, 0xaf, 0x68, 0xfd, 0x70, 0x9e, 0x3b, 0xa7, 0xff, 0x11,
	0xb6, 0x15, 0x50, 0x42, 0xc7, 0xec, 0x92, 0x2e, 0x8e, 0xfb, 0x05, 0xea, 0xd2, 0x64, 0xe6, 0xcf,
	0x78, 0x51, 0xb4, 0xbf, 0xc1, 0xc1, 0x1c, 0xf8, 0xa2, 0x04, 0x9c, 0x03, 0xca, 0xbf, 0x5a, 0x45,
	0x11, 0xff, 0x04, 0x3b, 0xd7, 0x60, 0x8b, 0x22, 0x4c, 0x60, 0xab, 0xf0, 0x32, 0x9f, 0x03, 0x3e,
	0x44, 0x6d, 0x29, 0x98, 0x19, 0x6c, 0x3e, 0x7c, 0x5d, 0xea, 0x78, 0x34, 0x8c, 0x06, 0xfe, 0xa4,
	0x30, 0xf6, 0x03, 0x38, 0xba, 0x23, 0x4d, 0x51, 0x82, 0x06, 0x70, 0x24, 0x75, 0xf5, 0x21, 0x35,
	0x0d, 0xa1, 0x79, 0x77, 0xa6, 0x82, 0x64, 0x5d, 0xac, 0xf2, 0xff, 0x93, 0x2f, 0xff, 0x05, 0x00,
	0x00, 0xff, 0xff, 0xe6, 0x16, 0xfe, 0x6e, 0x61, 0x0a, 0x00, 0x00,
}
